# Generated by Django 6.0.4 on 2026-04-26 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalityWise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locality", models.CharField(max_length=255, unique=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("persons_count", models.PositiveIntegerField(default=0)),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank", "Bank Transfer"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locality_summary",
                "ordering": ["locality"],
            },
        ),
        migrations.CreateModel(
            name="UserReg",
            fields=[
                ("sl_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("bs", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "locality",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("extra_stay", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("acc", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "acc_on_30th",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("acc_on_1_2", models.CharField(blank=True, max_length=100, null=True)),
                ("acc_3rd", models.CharField(blank=True, max_length=100, null=True)),
                ("transport", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "arrival_train_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "arrival_station",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "departure_train_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "departure_station",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "registration_balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "extra_stay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transportation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("bus_no", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_registration",
                "ordering": ["sl_no"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("regular", "Regular"),
                            ("staff", "Staff"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
